### ISSUE TITLE
snmp trap always sets severity to 'normal'

### ISSUE THREAD

**Issue by msupinodn** [alerta/alerta-contrib#111]
Severity probably needs some logic, but setting to normal as default wont show anything in the dashboard for open alerts.

**Comment by satterly** [comment]
As a first pass this should be changed to set severity to `indeterminate`.

Then, some example code should be included to show how a "plugin" can be used to lookup trapvars from the orginal snmp trap to set alert attributes to useful values.

**Comment by satterly** [comment]
README updated to include extensive trapvar lookup example. See https://github.com/alerta/alerta-contrib/tree/master/integrations/snmptrap#transform-plugin
