### ISSUE TITLE
Allow per Environment config for plugins

### ISSUE THREAD

**Issue by dguihal** [alerta/alerta-contrib#124]
Currently there is no way for the plugins to behave differently depending on some alert attributes, especially "environment" one. That would be great so staging-like could be monitored with the same alerta server as prod without pushing SMS notifications (by example)

**Comment by satterly** [comment]
This is possible by defining some "plugin routing rules". See http://docs.alerta.io/en/latest/gettingstarted/tutorial-3-plugins.html#step-3-route-alerts-to-plugins

**Comment by dguihal** [comment]
Oh great, that's definitively a good point, I will look at it.
But as far as I can see, there is no way to dynamically configure a plugin based on alerts attributes.

But anyway, thanks for the great job

**Comment by satterly** [comment]
No, you're right. None of the plugins available on this contrib repo allow you to have different configurations based on alert attributes. This is not something I've considered before and I don't see something like this being implemented any time soon. All of the plugins are just examples and you are free to fork and modify them to suit yourself. And if you consider that any of your enhancements may be useful to others you are encouraged to contribute them back. Thanks for the feedback.
