### ISSUE TITLE
Add integration for Rocket chat

### ISSUE THREAD

**Issue by satterly** [alerta/alerta-contrib#150]
see https://rocket.chat/

**Comment by judexzhu** [comment]
Please excuse me, is there any progress with this case?

**Comment by satterly** [comment]
No. I was hoping someone who knew something about Rocket Chat would be inspired to contribute. Having someone willing to test and give feedback would be appreciated though so let me know if you could help with that. Thanks.

**Comment by satterly** [comment]
Feedback welcome.
