### ISSUE TITLE
alerta does not start with PLUGIN = ['zabbix']

### ISSUE THREAD

**Issue by gabricar** [alerta/alerta-contrib#152]
I'm trying to configure this plugin but after adding PLUGIN = ['zabbix'] alerta does not start.
changed it to ['zabbix-alerta'] and at least it start but the scritp does not run.
Added DEBUG = True but I'm not seeing any meaningful logs at /var/log/messages. I've also tried to specify a log file but after adding LOG_FILE = /var/log/alerta.log alerta does not start.

In additional this script only works if you have only one zabbix server. I changed it to grab the environment variable from the alerta's ticket (alert_env = alert.attributes.get('environment', None)) and each environment was added as a zabbix server alias in the local hosts file. I hope this will do the trick

**Comment by satterly** [comment]
What version of alerta server are you running?

When I run alerta server version 5.0.0 with the plugin installed and added like so...
```
PLUGINS=['reject', 'blackout', 'zabbix']
```
I get an error saying it's not loaded because it isn't configured ...
```
--------------------------------------------------------------------------------
DEBUG in __init__ [/Users/nsatterl/Projects/alerta/alerta/plugins/__init__.py:47]:
Server plugin 'zabbix' installed.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in __init__ [/Users/nsatterl/Projects/alerta/alerta/plugins/__init__.py:57]:
Server plugin 'zabbix' could not be loaded: 'ZABBIX_API_URL'
--------------------------------------------------------------------------------
```
Do you see anything like that when you run `alertad` like this?
```
$ alertad run --debugger
```

**Comment by gabricar** [comment]
@satterly , I did an update on alerta and now I can start it with the option PLUGIN = ['zabbix']
alerta --debug
INFO in __init__ [/usr/lib/python2.7/site-packages/alerta/plugins/__init__.py:56]:
Server plugin 'zabbix' enabled.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in __init__ [/usr/lib/python2.7/site-packages/alerta/plugins/__init__.py:59]:
All server plugins enabled: zabbix

but it still does not work. the only thing that I'm seeing at the logs when I'm clicking at ack is
==> nginx/access.log <==
9.50.0.6 - - [15/Oct/2017:20:48:08 -0400] "PUT /api/alert/a87279c1-8b1e-4d87-ad99-ca0a97794346/status HTTP/1.1" 200 21 "http://172.16.0.123/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"

==> messages <==
Oct 15 20:48:08 alerta01 alertad: [pid: 12661|app: 0|req: 12/30] 9.50.0.6 () {52 vars in 1377 bytes} [Sun Oct 15 20:48:08 2017] PUT /api/alert/a87279c1-8b1e-4d87-ad99-ca0a97794346/status => generated 21 bytes in 13 msecs (HTTP/1.1 200) 2 headers in 71 bytes (2 switches on core 0)

==> nginx/access.log <==
9.50.0.6 - - [15/Oct/2017:20:48:08 -0400] "GET /api/alert/a87279c1-8b1e-4d87-ad99-ca0a97794346 HTTP/1.1" 200 3006 "http://172.16.0.123/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"

==> messages <==
Oct 15 20:48:08 alerta01 alertad: [pid: 12664|app: 0|req: 6/31] 9.50.0.6 () {46 vars in 1221 bytes} [Sun Oct 15 20:48:08 2017] GET /api/alert/a87279c1-8b1e-4d87-ad99-ca0a97794346 => generated 3006 bytes in 8 msecs (HTTP/1.1 200) 4 headers in 143 bytes (2 switches on core 0)

**Comment by satterly** [comment]
can you type `alerta version` for me and paste the result below? You should get something like ...
```
$ alerta version
alerta 5.0.0rc3
alerta client 5.0.5
requests 2.18.4
```

**Comment by gabricar** [comment]
Hi my alerta server was running on the version 4 I tried to upgrade but it is know broke. Let me rebuild this environment and get back to you. thx
after the pip install --upgrade alerta-server the environment does not start. I do have some logs but I think will be easier to start from scratch.

Oct 17 15:05:38 alerta01 alertad:  File "wsgi.py", line 1, in <module>
Oct 17 15:05:38 alerta01 alertad:
Oct 17 15:05:38 alerta01 alertad: from alerta.app import app
Oct 17 15:05:38 alerta01 alertad: ImportError
Oct 17 15:05:38 alerta01 alertad: :
Oct 17 15:05:38 alerta01 alertad: cannot import name app
Oct 17 15:05:38 alerta01 alertad:

Oct 17 15:05:39 alerta01 systemd: alerta-app.service: main process exited, code=exited, status=22/n/a
Oct 17 15:05:39 alerta01 systemd: Failed to start uWSGI service for Alerta.
Oct 17 15:05:39 alerta01 systemd: Unit alerta-app.service entered failed state.

**Comment by satterly** [comment]
ok. If you want more immediate feedback you can always use gitter chat https://gitter.im/alerta/chat

**Comment by gabricar** [comment]
@satterly you can close this bug. fixed after upgrade alerta-server
