### ISSUE TITLE
Plugins still using get_body()

### ISSUE THREAD

**Issue by wmturner** [alerta/alerta-contrib#166]
Hi,

Thank you for this great tool, and the work you have done.  A few (have not checked all yet) plugins are missing the fix you put in the AMQP plugin for the deprecated get_body() method.  I have fixed this in the SNS plugin, and can fix the rest of them for you in a PR if you like.

Best,
-William

**Comment by satterly** [comment]
Hi @wmturner , a quick "git grep" shows that it was used more widely than I realised...
```
$ git grep get_body
integrations/sqs/alerta_sqs.py:        LOG.info('SQS: Received message - %s' % message.get_body())
plugins/amqp/alerta_amqp.py:            body = alert.get_body()  # alerta < 5.0
plugins/opsgenie/alerta_opsgenie.py:        LOG.debug('Alert receive %s: %s' % (alert.id, alert.get_body(history=False)))
plugins/opsgenie/alerta_opsgenie.py:            details = alert.get_body(history=False)
plugins/opsgenie/alerta_opsgenie.py:        LOG.debug('Alert change %s: %s' % (alert.id, alert.get_body(history=False)))
plugins/pagerduty/alerta_pagerduty.py:            "details": alert.get_body(history=False)
plugins/pagerduty/alerta_pagerduty.py:            "details": alert.get_body(history=False)
plugins/sns/alerta_sns.py:        LOG.debug('Message: %s', alert.get_body())
plugins/sns/alerta_sns.py:        response = self.connection.publish(topic=self.topic_arn, message=alert.get_body())
```
which makes me think I should bring it back :( let me think about this and get back to you. thanks.

**Comment by satterly** [comment]
I have decided it was better to reinstate the `get_body()` method. Thanks for your work on this. Much appreciated.
