### ISSUE TITLE
Cloudwatch webhook in 4.8.4

### ISSUE THREAD

**Issue by Ursidae44** [alerta/alerta-contrib#174]
I'm using Alerta Server 4.8.4 and I'm trying to setup the webhook for Cloudwatch integration. I have setup an SNS topic and subscription and verified that I can reach the Alerta endpoint API. I tried to send a subscription confirmation but the confirmation never comes back.

I found the cloudwatch webhook in the source and it does seem to respond to the confirmations - so then I poked around and realized that the 4.8.4 installation I have doesn't have a cloudwatch.py in the app/webhooks directory. 

Is there something I have to do to add the webhook to my installation or enable it? The documentation suggests that it is a built-in webhook and doesn't indicate any further setup is required.

**Comment by satterly** [comment]
The webhook is there by default in release 4 ... https://github.com/alerta/alerta/blob/release-4.10.x/alerta/app/webhooks/views.py#L90

Are there any errors in the alerta server logs from the AWS callbacks?

Have you tried hitting the webhook URL using Curl ? eg `curl -X POST http://example.com/webhooks/cloudwatch -d {}` and seeing if you get a response or error?

**Comment by Ursidae44** [comment]
Thank you for the response. I was able to figure it out once I configured the logs and sent some test messages. It looks like the endpoint was working but the reject plugin wasn't letting any of the SNS messages through.
