### ISSUE TITLE
Logstash plugin broken (Python3)

### ISSUE THREAD

**Issue by eesprit** [alerta/alerta-contrib#184]
Hi,

I am trying to use the logstash plugin, but found out there are some problems with it :
- It does not convert the LOGSTASH_PORT env variable to int (I use the Docker version of alerta-web, so I configured it using env variables)
- The socket.send method want bytes and not string (seems to be a major change in Python3)

I have workaround the first problem, and even the second one (I'll do a PR when all is working fine), but I am having a hard time to understand what exactly should be sent to logstash... 

At first, the logstash plugin was sending this :
` self.sock.send("%s\r\n" % alert)`
So I changed it to : 
` self.sock.send(b"%s\r\n" % bytes(str(alert), 'utf-8'))`
It works well, but on the logstash/elasticsearch side, what I get is documents with a "message" attribute consisting of :
Alert(id='449b842a-cb94-420a-a53b-48eae9836816', environment='devel', resource='bacula', event='SystemLoad', severity='informational', status='open', customer=None)

Which of course does not really look like JSON documents...

Is it really what should be sent to logstash/ES ? I was expecting logstash to receive some JSON doc it would be able to parse.
Is there somewhere a more complete documentation ? (the only one I found is https://github.com/alerta/kibana-alerta/blob/master/README.md)

Thanks for your help.

**Comment by eesprit** [comment]
I got it working using : 
` self.sock.send(b"%s\r\n" % bytes(json.dumps(alert.get_body(history=False), default=str), 'utf-8'))`
Not sure if that is what was expected, but seems to work.

I also had to add this to my logstash.conf :
```
filter {
...
if [type] == "json" {
    json {
      source => "message"
      add_field => {
        "severity_label" => "%{severity}"
      }
      remove_field => [ "severity", "rawData" ]
    }
  }
...
}
```
Notes :
- the severity field renaming is only need in my case because we already use such a field but with a different type
- the rawData field was causing problems when logstash was pasring it, and i judged it useslees, so I removed it.

**Comment by eesprit** [comment]
I don't have a python 2.x build at hand to test.
It seems that python2 provides a "bytes()" method that act like "str()", so it might works.
I'll try to build a python2 Docker image and test, I'll keep you updated.

**Comment by satterly** [comment]
This is the problem with having to support python 2 and python 3 -- which won't be necessary soon (#480).

**Comment by satterly** [comment]
@eesprit I've got a possible fix. Can you test #186 and let me know? Thanks.

**Comment by eesprit** [comment]
I'll test it this morning.

In the meantime, I confirm that the actual plugin does not work with python2, because it doesn't send JSON data to logstash, but the Python representation of the Altert, wich logstash can't understand :
`[2018-04-17T09:56:00,747][WARN ][logstash.filters.json    ] Error parsing json {:source=>"message", :raw=>"Alert(id=u'ad109d81-e675-4ba1-8735-215ef4d6545b', environment=u'devel', resource=u'rancher3', event=u'SystemLoad', severity=u'warning', status=u'open', customer=None)\r", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'Alert': was expecting ('true', 'false' or 'null')`

It should have been broken during some refactoring at the Alert model level.

I'll check your patch ASAP with Python2 and Python3.

**Comment by eesprit** [comment]
It works for both version (py2 and py3) :thumbsup:
