### ISSUE TITLE
mailer alerts are in some cases never sent when alert is cleared

### ISSUE THREAD

**Issue by eesprit** [alerta/alerta-contrib#190]
The actual design of filtering the alerts (on_message function) works well in the basic use case of alerts going from critical/major to normal/ok/cleared.
But it does not work well with alerts transitionning through warning, and informational state, because it only considers cleared alerts coming from a previous state in critical or major.

For example : I am using alerts from kapacitor which sends alert of type info, warn and critical depending on the server load. Server load is not something that will go straight from critical to ok because that takes time.
So if the load is increasing, I'll get an Open/critical mail alert, when it calms down I'll get an Open/warning alert, but I'll never get a Closed/info, Closed/ok or Closed/cleared email alert, because the mailer integrations does not take into account those transitions.

I am working on a patch to fix that, but if you have recommandations on what should be done to do it for most people use-cases, I am all ears !
I am thinking on using the history of the alert to decide if we were previously in an alerting state or not.
That seems the better thing to do, as we don't want to send mail (but perhaps some will ? perhaps a config option ?) for alert trnsitioning from normal => informational => normal.
Perhaps a minimum alert threshold ?

**Comment by satterly** [comment]
This sounds like a good approach. Let me know if you need any help with this. I'll close this for now.
