### ISSUE TITLE
Slack plugin ignores blackout settings?

### ISSUE THREAD

**Issue by evaryont** [alerta/alerta-contrib#195]
It seems like the Slack plugin sends a message for all incoming alerts, regardless if that alert matches a blackout rule. Even with `NOTIFICATION_BLACKOUT` enabled.

**Comment by satterly** [comment]
set `NOTIFICATION_BLACKOUT` to `False` and then send an alert that should be suppressed by a blackout rule. If you don't get a response similar to the below then either you do not have `blackout` plugin enabled, the blackout rule is not matching or something else has gone wrong.

```
$ alerta send -E Development -S Foo -e e1 -r r1 -s warning
1ab4f2dc-e8d7-4dcf-9232-7370ba474458 (Suppressed alert during blackout period)
```
