### ISSUE TITLE
alerta-urlmon uses Python2 libs

### ISSUE THREAD

**Issue by silvatyrant** [alerta/alerta-contrib#198]
This causes certain incompatibility issues when trying to use the integration with the Docker image.

**Comment by silvatyrant** [comment]
Testing the following changes:
`import urllib2` becomes `import urllib` on ln 5
`import Queue` becomes 
`
try:
        import queue
 except ImportError:
        import Queue as queue
` on ln 10
`from BaseHTTPServer import BaseHTTPRequestHandler as BHRH` becomes `from http.server import BaseHTTPRequestHandler as BHRH` on ln 14

**Comment by satterly** [comment]
Can you submit these changes as a pull request? That would be really helpful. Thanks.

**Comment by silvatyrant** [comment]
Hi Nick,

I've since realised that in the "Docker world" URLMon needs to run inside
it's own container. And thus, these changes are not required. I will close
this issue.

Apologies.

Kind regards,

Alain Williams
email: silvatyrant@gmail.com
cell: +27 83 3089658
