### ISSUE TITLE
Cachet plugin - Visible tag

### ISSUE THREAD

**Issue by fabius87** [alerta/alerta-contrib#232]
**Is possibile to add the possibility to overwrite default VISIBLE status when an alert from Alerta is sent to cachet?**
My problem is that each alert is being publish with tag VISIBLE=True but I'd like to discriminate if an issue must be set VISIBLE=True (for example if alert is a functionality deserver) or must be set VISIBLE=False (for example if alert is just an internal alert, for technician team or something similar).

**What I expect**
My idea is to add, in Alerta, a tag called VISIBLE with different boolean value for each alert. In this way Cachet plugin can read this value and add incident to public dashboard or to private dashboard.

Sorry for my English,

Thank you
Fabius87

**Comment by satterly** [comment]
Yes, just use a `tag` or custom `attribute` and set the value based on whatever logic you want in the cache plugin before forwarding to Cachet. Let me know if you need more info.

**Comment by yuvarajan1989k** [comment]
Hi,

i want to add some additional attributes before passing the alerts data to cahcet plugin. may I know how to do this ?

**Comment by satterly** [comment]
Like this...

https://github.com/alerta/alerta-contrib/blob/c4a253e64454ba757846e7ca46081d40e3c91a41/plugins/geoip/alerta_geoip.py#L34-L37

**Comment by yuvarajan1989k** [comment]
thanks for the update.

I am using the stackdriver webhook to update the alerta. Then the alerta is updating to cachethq. Here  I want to add some custom attributes before updating the cachetapi.

I try to follow your suggestion. FYI

alert.attributes = {
                   'component_id': alert.component_id
                    'component_status': alert.component_status
                   }

But I received the following error.

 alertad: 2020-04-28 15:50:29,055 alerta.app[15777]: [ERROR] 'Alert' object has no attribute 'component_id' 


Kindly guide me on this. thank you.

**Comment by yuvarajan1989k** [comment]
Above one is fixed. thank you.
