### ISSUE TITLE
Plugin Not Load

### ISSUE THREAD

**Issue by marcodesantis71** [alerta/alerta-contrib#240]
Hi All

I've installed InfluxDB on my Ubuntu 16 with Alerta.

When I start uwsgi I found this error on my syslog:

ERROR - Server plugin 'influxdb' could not be loaded: 'influxdb' [in /opt/alerta/lib/python3.5/site-packages/alerta/utils/plugin.py:40]

I've installed with this command:

pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/influxdb

And I add the instructions on my Alerta.conf

PLUGINS = ['reject', 'influxdb']

Please, help me.
Thx.

**Comment by satterly** [comment]
How did you install Alerta? Into a virtual environment? If so you need to install the plugin into the same python virtual environment. 

To check, you can run `pip list | grep alerta` and you should see the `alerta-sever` as well as any plugins you have installed like so ...
```
$ pip list | grep alerta
alerta-geoip              5.3.2     /Users/nsatterl/Projects/alerta-contrib/plugins/geoip
alerta-gitlab             6.1.0     /Users/nsatterl/Projects/alerta/contrib/plugins/gitlab
alerta-logstash           5.3.3     /Users/nsatterl/Projects/alerta-contrib/plugins/logstash
alerta-prometheus         5.4.0     /Users/nsatterl/Projects/alerta-contrib/plugins/prometheus
alerta-sentry             5.0.0     /Users/nsatterl/Projects/alerta-contrib/webhooks/sentry
alerta-server             6.7.3     /Users/nsatterl/Projects/alerta
```

**Comment by marcodesantis71** [comment]
Hi,
thx.

Now Alerta loaded the plugin.

Feb 13 10:52:21 VM-ALERTA alertad: 2019-02-13 10:52:21,496 - raven.base.Client[7401]: INFO - Raven is not configured (logging is disabled). Please see the documentation for more information. [in /opt/alerta/lib/python3.5/site-packages/raven/base.py:218]
Feb 13 10:52:21 VM-ALERTA alertad: 2019-02-13 10:52:21,602 - alerta.plugins[7401]: INFO - Server plugin 'reject' enabled. [in /opt/alerta/lib/python3.5/site-packages/alerta/utils/plugin.py:38]
Feb 13 10:52:21 VM-ALERTA alertad: 2019-02-13 10:52:21,618 - alerta.plugins[7401]: INFO - Server plugin 'influxdb' enabled. [in /opt/alerta/lib/python3.5/site-packages/alerta/utils/plugin.py:38]
Feb 13 10:52:21 VM-ALERTA alertad: 2019-02-13 10:52:21,618 - alerta.plugins[7401]: INFO - All server plugins enabled: reject, influxdb [in /opt/alerta/lib/python3.5/site-packages/alerta/utils/plugin.py:41]
Feb 13 10:52:21 VM-ALERTA alertad: 2019-02-13 10:52:21,623 - alerta.plugins[7401]: INFO - No plugin routing rules found. All plugins will be evaluated. [in /opt/alerta/lib/python3.5/site-packages/alerta/utils/plugin.py:45]

I'm testing on two VM.
On InfluxDB VM I installed telegraf and I can see that the disk space is full.
On Alerta VM, I've not alarm.

This is my configuration:

INFLUXDB_DSN = 'influxdb://10.211.55.14:8086'
INFLUXDB_DATABASE = 'telegraf'
INFLUXDB_MEASUREMENT = 'disk'

Where I wrong?

**Comment by satterly** [comment]
I assume you fixed this. Let me know if you need any more help.
