### ISSUE TITLE
Testing new webhook

### ISSUE THREAD

**Issue by sauber** [alerta/alerta-contrib#241]
How is it possible to test a webhook? I'm considering to write a new one for rancher. This is how far I got testing the existing azuremonitor webhook:

```
git clone https://github.com/alerta/alerta-contrib.git
cd alerta-contrib/webhooks/azuremonitor
python3 setup.sh install
cd
git clone https://github.com/alerta/alerta.git
cd alerta
export FLASK_APP=alerta FLASK_ENV=development
flash run
# In other terminal
~$ curl -s http://127.0.0.1:8080 | grep azure
      "href": "http://127.0.0.1:8080/webhooks/azuremonitor", 
      "rel": "webhooks.azuremonitor"
~$ curl -X POST http://127.0.0.1:8080/webhooks/azuremonitor
{
  "code": 404, 
  "errors": null, 
  "message": "Webhook 'azuremonitor' not found. Did you mean to use POST instead of GET?", 
  "status": "error"
}

**Comment by satterly** [comment]
I've worked out what might be going wrong. The error message is misleading as it suggests that the webhook isn't being loaded. It might be loading ok but the actual webhook may be generating a `KeyError` exception which is being misinterpreted as the error you are seeing. I will fix this to make the error more explicit and include an example test case for webhooks.

**Comment by satterly** [comment]
I've just added a test case to the Sentry webhook. Use that as a starting point for your webhook.

To run your test do something like this if using postgres (db must be running)...
```
$ pip install -r requirements-dev.txt
$ createdb test5
$ ALERTA_SVR_CONF_FILE= DATABASE_URL=postgres:///test5 pytest -v webhooks/azuremonitor
```

Or if using MongoDB (mongodb must be running)...
```
$ pip install -r requirements-dev.txt
$ ALERTA_SVR_CONF_FILE= pytest -v webhooks/azuremonitor
```
