### ISSUE TITLE
SLACK_CHANNEL_ENV_MAP from env_vars is broken in slack plugin

### ISSUE THREAD

**Issue by seasurfpete** [alerta/alerta-contrib#250]
**Describe the bug**
Loading of the {'env', '#channel'} string via env var is broken and is loading the value as a string.

looking at the code the os.environ.get() should probably be wrapped in a json.loads() - obviously will fail if not valid json.

**To Reproduce**
set SLACK_CHANNEL_ENV_MAP = {'env', '#channel'} in container env settings.
start alerta and load plugin
trigger an alert and watch debug logs

**Expected behavior**
routing of slack messages are determined by the map

**Actual Resuls**
ERROR:alerta.plugins.slack:Exception formatting payload: 'str' object has no attribute 'get'
  File "/venv/lib/python3.6/site-packages/alerta_slack.py", line 158, in post_receive
    payload = self._slack_prepare_payload(alert)
  File "/venv/lib/python3.6/site-packages/alerta_slack.py", line 92, in _slack_prepare_payload
    channel = SLACK_CHANNEL_ENV_MAP.get(alert.environment, SLACK_CHANNEL)

**Environment:**
- Docker Alerta image 
- openshift (kubernetes 1.9) 3.9 

**Additional context**
This problem came about when trying to setup multiple slack webhooks to route messages to different boards. This obviously isn't supported so channel routing was tested.

**Comment by satterly** [comment]
Thanks for raising this issue. Is this something you think you could fix yourself?

**Comment by seasurfpete** [comment]
Hi nick. Yes I can post a fix if you like.
