### ISSUE TITLE
Getting syntax error for msteams

### ISSUE THREAD

**Issue by irom77** [alerta/alerta-contrib#257]
See below, xxx to mask: 

```
File "/app/alertad.conf", line 4
    MS_TEAMS_WEBHOOK_URL = https://outlook.office.com/webhook/xxx/IncomingWebhook/xxx
                                ^
SyntaxError: invalid syntax
```

**Comment by satterly** [comment]
You need to surround the URL in quotes. See https://docs.alerta.io/en/latest/configuration.html#general-settings and http://flask.pocoo.org/docs/1.0/config/#configuring-from-files

**Comment by irom77** [comment]
I surrounded it in quotes, but apparently when using docker-alerta (in particular kubernetes) , I had to use double quotes , like that "'https://hooks.slack.com/services/xxx/xxx/xxx'" ;)

**Comment by satterly** [comment]
Weird. Not seen that before.
