### ISSUE TITLE
Alerta-mailer plugin unable to send html mails

### ISSUE THREAD

**Issue by Komalgupta22722** [alerta/alerta-contrib#260]
my config file   settings.py:  
DEFAULT_OPTIONS = {
'config_file': '/mailer.conf',
'profile': None,
'endpoint': 'http://10.0.140.146:8080',
'key': '',
'amqp_url': 'redis://localhost:6379/',
'amqp_topic': 'notify',
'amqp_queue_name': '', # Name of the AMQP queue. Default is no name (default queue destination).
'amqp_queue_exclusive': True, # Exclusive queues may only be consumed by the current connection.
'smtp_host': 'smtp.gmail.com',
'smtp_port': 587,
'smtp_username': '', # application-specific username if it differs from the specified 'mail_from' user
'smtp_password': '', # application-specific password if gmail used
'smtp_starttls': True, # use the STARTTLS SMTP extension
'smtp_use_ssl': False, # whether or not SSL is being used for the SMTP connection
'ssl_key_file': None, # a PEM formatted private key file for the SSL connection
'ssl_cert_file': None, # a certificate chain file for the SSL connection
'mail_from': '', # alerta@example.com
'mail_to': [], # devops@example.com, support@example.com
'mail_localhost': None, # fqdn to use in the HELO/EHLO command
'mail_template_html': '/templates/email2.html.tmpl',
'mail_template': '/templates/email.tmpl',
'mail_subject': ('[{{ alert.status|capitalize }}] {{ alert.environment }}: '
'{{ alert.severity|capitalize }} {{ alert.event }} on '
'{{ alert.service|join(\',\') }} {{ alert.resource }}'),
'dashboard_url': 'http://10.0.140.146:3000',
'debug': False,
'skip_mta': False,
'email_type': 'html' # options are: text, html
}

Mailer.conf:

[alerta-mailer]
key = SG.QqdicSaVR1WD787WB5BQpw.IeP_fj66BbealdkUHZVrN2GOZtRBpV4fs8tz-XUmD2
smtp_host = smtp.sendgrid.net
smtp_port = 25
mail_to = komgupta@paytm.com
mail_from = komalg038@abc.com
amqp_url = mongodb://localhost:27017/kombu
dashboard_url = http://10.0.140.146:3000
smtp_username = usrrname
smtp_password = Pass
smtp_use_ssl = False
debug = True
skip_mta = True
email_type = html

**Comment by Komalgupta22722** [comment]
I have used alerta-mailer plugins and it doesn't sends mails in html format.... First it demands for both the values mail_template as well as mail-template_html but it displays the results in the format which is defined in mail_template.. I have changed email-type as html also in my alerta-config file and settings.py

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by satterly** [comment]
See #261

**Comment by Komalgupta22722** [comment]
Please look at issue 261 and close this..
And explain what info you need
