### ISSUE TITLE
Alerta mailer plugin is t sendings mails of type html

### ISSUE THREAD

**Issue by Komalgupta22722** [alerta/alerta-contrib#261]
**Issue Summary**
I have used alerta-mailer plugins and it doesn't sends mails of html type, it only sends mails of type= text...When I comment out the mail_template key it gives the error: "mail_template missing" so I am keeping both the keys mail_template as well as mail_template_html in my config and sets the email_type as html but it displays the results in the text format and taking the path of the file which is defined in key mail_template....... I have changed email-type as html  in my alerta-config file and `settings.py`

**Environment**
- OS: Linux
- API version: [eg. 6.8.1]
- Deployment: on my local machine
- For self-hosted, WSGI environment: No env

- Database: mongo

- Server config:
  Auth enabled? n
  Auth provider? n
  Customer views? n
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
1. Go to 'mailer.py' and change the email_type as html and set the mail_template_html path to your html file
2. Go to mailer.conf file and change the email_type as html
 and run alerta-mailer
3. Now alert is sent but the alert is in the format which is mentioned in the path of mail_template variable in mailer.py not in the format of the path in mail_template_html

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
As I have setted the email type as html so it should read the key mail_template_html and sends the file contents in html format

**Screenshots**

**Additional context**

MY mailer.py file:

```
DEFAULT_OPTIONS = {
    'config_file':   '/mailer.conf',
    'profile':       None,
    'endpoint':      'http://10.0.140.146:8080',
    'key':           '',
    'amqp_url':      'redis://localhost:6379/',
    'amqp_topic':    'notify',
    'amqp_queue_name':    '', # Name of the AMQP queue. Default is no name (default queue destination).
    'amqp_queue_exclusive': True, # Exclusive queues may only be consumed by the current connection.
    'smtp_host':     'smtp.gmail.com',
    'smtp_port':     587,
    'smtp_username': '', # application-specific username if it differs from the specified 'mail_from' user
    'smtp_password': '',  # application-specific password if gmail used
    'smtp_starttls': True,  # use the STARTTLS SMTP extension
    'smtp_use_ssl': False,  # whether or not SSL is being used for the SMTP connection
    'ssl_key_file': None, # a PEM formatted private key file for the SSL connection
    'ssl_cert_file': None, # a certificate chain file for the SSL connection
    'mail_from':     '',  # alerta@example.com
    'mail_to':       [],  # devops@example.com, support@example.com
    'mail_localhost': None,  # fqdn to use in the HELO/EHLO command
    'mail_template_html': '/templates/email2.html.tmpl', 
    'mail_template':  '/templates/email.tmpl',
    'mail_subject':  ('[{{ alert.status|capitalize }}] {{ alert.environment }}: '
                      '{{ alert.severity|capitalize }} {{ alert.event }} on '
                      '{{ alert.service|join(\',\') }} {{ alert.resource }}'),
    'dashboard_url': 'http://10.0.140.146:3000',
    'debug':         False,
    'skip_mta':      False,
    'email_type':    'html'  # options are: text, html
}

OPTIONS = {}
```

MY MAILER.CONF file:
```
[alerta-mailer]
smtp_host = smtp.sendgrid.net
smtp_port = 25
mail_to = komal2.gupta@paytm.com
mail_from = komalg038@abc.com
amqp_url = mongodb://localhost:27017/kombu
dashboard_url = http://10.0.140.146:3000
smtp_username = Rislra
smtp_password = YfE2
smtp_use_ssl = False
debug = True
skip_mta = True
email_type = html
```

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by Komalgupta22722** [comment]
EBUG:mailer:Looking for rules files in /mailer.conf.d/alerta.rules.d
DEBUG:mailer:Parsing alerts.json
INFO:mailer:Adding rule {'name': 'foo', 'fields': [{'field': 'resource', 'regex': '197nodnb22722'}], 'contacts': ['komal2.gupta@paytm.com']} to list of rules to be evaluated
DEBUG:mailer:Looking for rules files in //alerta.rules.d
DEBUG:mailer:Parsing alerts.json
ERROR:mailer:Could not parse file
Traceback (most recent call last):
  File "/home/komalgupta/.local/lib/python3.6/site-packages/mailer.py", line 423, in parse_group_rules
    rules = validate_rules(json.load(f))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 5 column 59 (char 109)
Python dns.resolver unavailable. The skip_mta option will be forced to False'mail_template'

**Comment by Komalgupta22722** [comment]
And when I keep both the variables mail_template as well as mail_template_html it is sending alerts and logs look like this:

DEBUG:mailer:Looking for rules files in /mailer.conf.d/alerta.rules.d
DEBUG:mailer:Parsing alerts.json
INFO:mailer:Adding rule {'name': 'foo', 'fields': [{'field': 'resource', 'regex': '197nodnb22722'}], 'contacts': ['komal2.gupta@paytm.com']} to list of rules to be evaluated
DEBUG:mailer:Looking for rules files in //alerta.rules.d
DEBUG:mailer:Parsing alerts.json
ERROR:mailer:Could not parse file
Traceback (most recent call last):
  File "/home/komalgupta/.local/lib/python3.6/site-packages/mailer.py", line 423, in parse_group_rules
    rules = validate_rules(json.load(f))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 5 column 59 (char 109)
INFO:kombu.mixins:Connected to mongodb://localhost:27017/kombu
Connected to mongodb://localhost:27017/kombu
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.0.140.146
Starting new HTTP connection (1): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (2): 10.0.140.146
Starting new HTTP connection (2): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (3): 10.0.140.146
Starting new HTTP connection (3): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (4): 10.0.140.146
Starting new HTTP connection (4): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (5): 10.0.140.146
Starting new HTTP connection (5): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (6): 10.0.140.146
Starting new HTTP connection (6): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (7): 10.0.140.146
Starting new HTTP connection (7): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (8): 10.0.140.146
Starting new HTTP connection (8): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (9): 10.0.140.146
Starting new HTTP connection (9): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (10): 10.0.140.146
Starting new HTTP connection (10): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (11): 10.0.140.146
Starting new HTTP connection (11): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (12): 10.0.140.146
Starting new HTTP connection (12): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (13): 10.0.140.146
Starting new HTTP connection (13): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (14): 10.0.140.146
Starting new HTTP connection (14): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (15): 10.0.140.146
Starting new HTTP connection (15): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (16): 10.0.140.146
Starting new HTTP connection (16): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (17): 10.0.140.146
Starting new HTTP connection (17): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (18): 10.0.140.146
Starting new HTTP connection (18): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (19): 10.0.140.146
Starting new HTTP connection (19): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (20): 10.0.140.146
Starting new HTTP connection (20): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (21): 10.0.140.146
Starting new HTTP connection (21): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (22): 10.0.140.146
Starting new HTTP connection (22): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (23): 10.0.140.146
Starting new HTTP connection (23): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (24): 10.0.140.146
Starting new HTTP connection (24): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (25): 10.0.140.146
Starting new HTTP connection (25): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (26): 10.0.140.146
Starting new HTTP connection (26): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (27): 10.0.140.146
Starting new HTTP connection (27): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (28): 10.0.140.146
Starting new HTTP connection (28): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (29): 10.0.140.146
Starting new HTTP connection (29): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (30): 10.0.140.146
Starting new HTTP connection (30): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (31): 10.0.140.146
Starting new HTTP connection (31): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (32): 10.0.140.146
Starting new HTTP connection (32): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (33): 10.0.140.146
Starting new HTTP connection (33): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (34): 10.0.140.146
Starting new HTTP connection (34): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (35): 10.0.140.146
Starting new HTTP connection (35): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (36): 10.0.140.146
Starting new HTTP connection (36): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (37): 10.0.140.146
Starting new HTTP connection (37): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (38): 10.0.140.146
Starting new HTTP connection (38): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (39): 10.0.140.146
Starting new HTTP connection (39): 10.0.140.146
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (40): 10.0.140.146
Starting new HTTP
