### ISSUE TITLE
Alerta deployment using uwsgi server

### ISSUE THREAD

**Issue by Komalgupta22722** [alerta/alerta-contrib#264]
**Issue Summary**
I have followed this url:http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html for deploying alerta on my centos server but getting the following error when I visit the UI : 

ERROR: Failed to connect to Alerta API due to missing or invalid config.json file.

Please confirm a config.json file exists, contains an "endpoint" setting and is in the same directory as the application index.html file.

**Environment**
- OS: Centos [eg. Linux, Mac, Windows]
- API version:  6.8.1
- Deployment: self-hosted
- For self-hosted, WSGI environment:  nginx with uwsgi,

- Database:  MongoDB

- Server config:
  Auth enabled? N
  Auth provider? N
  Customer views?N
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
2. Click on '....' or Run '...'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

Whenever I am changing the endpoint from {"endpoint": "/api"} to
{"endpoint": "http://10.143.42.233:8080"} my alerta is working 

Also  my uwsgi server and nginx is running fine. I have created a user also (www-data)
Contents of "uswgi.py file":
from alerta import app

Content of "/etc/uwsgi.ini":
[uwsgi]
chdir = /var/www
mount = /api=wsgi.py
callable = app
manage-script-name = true
env = BASE_URL=/api

master = true
processes = 5
logger = syslog:alertad

socket = /tmp/uwsgi.sock
chmod-socket = 664
uid = www-data
gid = www-data
vacuum = true

die-on-term = true

Content of "uwsgi service file":
[Unit]
Description=uWSGI service

[Service]
ExecStart=/opt/alerta/bin/uwsgi --ini /etc/uwsgi.ini

[Install]
WantedBy=multi-user.target

**Comment by satterly** [comment]
You haven't included the nginx config.

**Comment by Komalgupta22722** [comment]
This is done for now, but my plugins are not working
I have integrated pagerduty plugin which is working fine on my localsetup(without uwsgi server) but not on production with uwsgi server

**Comment by satterly** [comment]
Open a new issue for that please
