### ISSUE TITLE
Ack not working for Zabbix 4.0

### ISSUE THREAD

**Issue by gabricar** [alerta/alerta-contrib#265]
After upgrading my Zabbix from 3.0 to 4.0 the Alerta option to ACK alerts does not work anymore.

I think this is the issue.

Looking at the API call from 3.0 and 4.0 regarding the ACK 

3.0 has
{
    "jsonrpc": "2.0",
    "method": "event.acknowledge",
    "params": {
        "eventids": "20427",
        "message": "Problem resolved."
    },
    "auth": "038e1d7b1735c6a5436ee9eae095879e",
    "id": 1
}

4.0 has
{
    "jsonrpc": "2.0",
    "method": "event.acknowledge",
    "params": {
        "eventids": "20427",
        **"action": 6,**
        "message": "Problem resolved."
    },
    "auth": "038e1d7b1735c6a5436ee9eae095879e",
    "id": 1
}

Looks like an "action" is needed for the 4.0 API call.

Not sure how it can be fixed for me as I have a mixed environment of 3.0 and 4.0.

**Comment by satterly** [comment]
The zabbix two-way integration plugin uses the pyZabbix. Someone raised the exact issue here ... https://github.com/lukecyca/pyzabbix/issues/111 and it seems that acking in 4.0 just requires an additional parameter.

**Comment by satterly** [comment]
This should fix it c6ba21f702f06c226e1f3cb7c475525dbfea05c0 Can you test?

**Comment by gabricar** [comment]
Amazing!! It works. Thank you very much @satterly

**Comment by valumar** [comment]
> This should fix it [c6ba21f](https://github.com/alerta/alerta-contrib/commit/c6ba21f702f06c226e1f3cb7c475525dbfea05c0) Can you test?

This FIX brokes Zabbix 3. integration... Please reopen issue and fix for both 3.x and 4.x Zabbix
