### ISSUE TITLE
Question: telegram dynamic config ?

### ISSUE THREAD

**Issue by jjh74** [alerta/alerta-contrib#289]
Hi,
I was thinking about updating telegram plugin for dynamic config. I see couple of ways of doing this:
- on each "post_receive" create a new bot
- or create a new bot for each TELEGRAM_TOKEN and keep bots in dict indexed by token. Something like:
```python
self.bots = {}
bot = self.bots.get('TELEGRAM_TOKEN', None)
if not bot:
    bot = telepot.Bot(TELEGRAM_TOKEN)
    self.bots['TELEGRAM_TOKEN'] = bot
```
Do you have a better idea ?

At the moment I don't have good ideas on how the telegram _webhook_ can know which token/chat_id to use when sending "dynamic" replies ? I guess the plugin part should somehow encode token/chat_id to `callback_data` ? Or is it ok for now only to update the plugin and leave webhook with static config ?

**Comment by satterly** [comment]
I'm sorry but are you talking about the telegram [plugin](https://github.com/alerta/alerta-contrib/blob/master/plugins/telegram/README.md) or [webhook](https://github.com/alerta/alerta/blob/master/alerta/webhooks/telegram.py) or both?

Can you describe the step-by-step process that you are trying to fix?
Example
1. alert received
2. sent to telegram channel #foo
3. user acks alert in telegram
4. webook receives ack action and acks alert
etc.

**Comment by jjh74** [comment]
I'm talking about the [plugin](https://github.com/alerta/alerta-contrib/blob/master/plugins/telegram/README.md). I'd like to have dynamic/per message config so it would be possible to dynamically set token/chat_id(channel) for outgoing alerts.

So for example (plugin part):
1. alert1 comes in and routing plugin sets TELEGRAM_TOKEN 1 based on environment/customer/etc
2. telegram plugin sends alert1 using TOKEN 1
3. alert2 comes in and routing plugin sets different TELEGRAM_TOKEN 2
4. telegram plugin sends alert2 using TOKEN 2

But from here I think webhook comes in to play:
5. user clicks ack (alert1) in telegram
6. webhook receives ack(alert1) and sends [send_message_reply](https://github.com/alerta/alerta/blob/master/alerta/webhooks/telegram.py) using os.environ.get('TELEGRAM_TOKEN') or current_app.config.get('TELEGRAM_TOKEN'). AFAIK if this token/chat_id is different from token1/2(from steps 1-4) the reply can go to wrong chat/channel ?

So I guess what I'm trying to ask is does dynamic/per-message config for [plugin](https://github.com/alerta/alerta-contrib/blob/master/plugins/telegram/README.md) make sense if the [webhook](https://github.com/alerta/alerta/blob/master/alerta/webhooks/telegram.py) doesn't also have dynamic config ?

**Comment by satterly** [comment]
I don't think the token/chat_id is relevant for the webhook callback. As long as the alert id is passed to Alerta the alert will be actioned appropriately.

**Comment by jjh74** [comment]
Ok thanks. After reading the [webhook](https://github.com/alerta/alerta/blob/master/alerta/webhooks/telegram.py) code I thought that when user clicks telegram message inline keyboard then telegram sends action + alert_id to webhook and the webhook updates(Line84) alert in alertaDB and then sends back a reply(Line92) to telegram.

(BTW in [webhook](https://github.com/alerta/alerta/blob/master/alerta/webhooks/telegram.py) if Line78 returns None then Lines84/86 alert.set_status / alert.untag can fail ?
Should Line79/80 be: `if not alert and action != 'blackout': ... return jsonify(...`)

Do you have preference about the [plugin](https://github.com/alerta/alerta-contrib/blob/master/plugins/telegram/README.md) how the dynamic/per message config should work (first part of my original question):
- on each "post_receive" create a new bot
- or create a bot for each token and keep bots in dict.

**Comment by satterly** [comment]
>(BTW in webhook if Line78 returns None then Lines84/86 alert.set_status / alert.untag can fail ?
Should Line79/80 be: if not alert and action != 'blackout': ... return jsonify(...)

Yes. This looks like a bug. Please raise a PR to fix.

And I'm not sure how/why you need to create a new bot every time you get an alert. Why is that necessary?

**Comment by jjh74** [comment]
> > (BTW in webhook if Line78 returns None then Lines84/86 alert.set_status / alert.untag can fail ?
> > Should Line79/80 be: if not alert and action != 'blackout': ... return jsonify(...)
> 
> Yes. This looks like a bug. Please raise a PR to fix.

Done (https://github.com/alerta/alerta/pull/1036)
 
> And I'm not sure how/why you need to create a new bot every time you get an alert. Why is that necessary?

Good question, AFAIK [telepot](https://github.com/nickoala/telepot/tree/master/telepot) doesn't have a function for changing token. And I think different token is needed to send messages as different bots. (Possible use case for this would be to use different bot/chat_id for different environment or customers). Creating a new bot was an idea to get around not being able to change token.

At the moment I can live with one bot and dynamically only change TELEGRAM_CHAT_ID / TELEGRAM_TEMPLATE (these should be fairly straightforward to modify for dynamic/per message config).

**Comment by oktayaa** [comment]
@jjh74 
You said:
"At the moment I can live with one bot and dynamically only change TELEGRAM_CHAT_ID / TELEGRAM_TEMPLATE (these should be fairly straightforward to modify for dynamic/per message config)."

Do you have an example config for doing things like this?

**Comment by jjh74** [comment]
@oktayaa I don't have an example for telegram, but with MS teams I've used something like this(routing plugin/`routing.py`):
```
import logging

def rules(alert, plugins):
    LOG = logging.getLogger('alerta.plugins')
    if 'sometext/' in alert.origin:
        LOG.debug("using origin sometext")
        return [
            plugins['remote_ip'],
            plugins['reject'],
            plugins['heartbeat'],
            plugins['blackout'],
            plugins['telegram'],
            plugins['msteams']
        ], dict(MS_TEAMS_WEBHOOK_URL='https://redacted.webhook.office.com/webhookb2/redacted/IncomingWebhook/something')
    else:
        LOG.debug("using default origin w/out telegram plugin")
        return [
            plugins['remote_ip'],
            plugins['reject'],
            plugins['heartbeat'],
            plugins['blackout'],
            plugins['msteams']
        ], dict(MS_TEAMS_WEBHOOK_URL='https://redacted.webhook.office.com/webhookb2/redacted/IncomingWebhook/somethingelse')
```
Maybe something similar would work for telegram (`returning dict(TELEGRAM_CHAT_ID...)`). I'm not sure if overriding `TELEGRAM_TEMPLATE` works as is, because the telegram plugin seems to read the template on `__init__` (https://github.com/alerta/alerta-contrib/blob/master/plugins/telegram/alerta_telegram.py#L68-L76)
