### ISSUE TITLE
How to install slack plugin?

### ISSUE THREAD

**Issue by minhdanh** [alerta/alerta-contrib#29]
I follow the general instruction (`cd plugins/slack && python setup.py install`) but this doesn't install slack plugin to plugin directory of alerta (https://github.com/guardian/alerta).

I tried to copy file `slack.py` directly to `alerta/plugins`, then update the variable `PLUGINS` to include slack but the server log show that it wasn't loaded after re-deploying.
A little confused on how to install these kind of plugin.

**Comment by satterly** [comment]
I've fixed a bug and added a `README` file. Can you try again?

**Comment by minhdanh** [comment]
I deployed Alerta server on heroku, so how can I run `python setup.py install`?

**Comment by satterly** [comment]
Ok, this is a different problem. I need to investigate how to modify the python `requirements.txt` file Heroku uses to install the list of required packages.

**Comment by satterly** [comment]
It seems there's no way to do this just for Heroku so I've added `alerta-slack` to the `requirements.txt` for now. You will need to upgrade to Alerta server version 4.7.21 and add two Heroku config variables called `PLUGINS` and `SLACK_WEBHOOK_URL`. See example below...

<img width="846" alt="screen shot 2016-05-23 at 23 55 25" src="https://cloud.githubusercontent.com/assets/615057/15487068/1cb12ac6-2142-11e6-868e-6078d7c11bf2.png">

**Comment by minhdanh** [comment]
Thanks @satterly
I'll give it a try.
