### ISSUE TITLE
Multiple Alertmanagerrs

### ISSUE THREAD

**Issue by darkl0rd** [alerta/alerta-contrib#301]
It is not uncommon to run multiple alertmanagers, think for example a cluster of alertmanagers for each region you are hosting services in.

The current plugin allows you to only target a single AlertManager.

We use Alerta to group/visualize all our alerts from different monitoring systems and from different alertmanagers - it would be very convenient if this plugin would allow one to silence/ack the alerts for each respective alertmanager.

**Comment by satterly** [comment]
Could be relevant to alerta/alerta#1147
