### ISSUE TITLE
Zabbix event doesn't get closed if it's not acked before closing

### ISSUE THREAD

**Issue by burakksglu** [alerta/alerta-contrib#307]
**Issue Summary**
Zabbix event doesn't get closed if it's not acked before closing

**Environment**
- OS: Linux
- API version: 4.0
- Deployment: Docker
- For self-hosted, WSGI environment: Whatever docker works with

- Database: Postgres

- Server config:
  Auth enabled? No
  Auth provider? 
  Customer views? No

- web UI version: 7.4.1
- CLI version:  7.4.1

**To Reproduce**
1. Select a Zabbix generated alert in Alerta
2. Click on close in Alerta (do not ack before this step)
3. It will be closed on alerta but will stay open zabbix

Root cause seems to be selecting only acknowledged events from zabbix in the line below:

https://github.com/alerta/alerta-contrib/blob/0836ac391e892eb51480c1407bf4a3b24a88767d/plugins/zabbix/alerta_zabbix.py#L87

This doesn't bring the original event thus it is not closed.

Thanks.

**Comment by satterly** [comment]
Thanks for raising this issue. Is this something you think you could fix yourself?

**Comment by burakksglu** [comment]
I am not familiar with Zabbix api but I can help if you need anything from my side.

**Comment by satterly** [comment]
All you need to do is submit the code snippet above as a PR and test it. Then I'll merge. Easy.

**Comment by burakksglu** [comment]
Alright, I'll try to have a look this week when I have time.

**Comment by satterly** [comment]
Fixed by d18494b812bc0fcc0cab4cc3b2f288f31d4938cd
