### ISSUE TITLE
Adding extra tags to OpsGenie

### ISSUE THREAD

**Issue by mustaqeem** [alerta/alerta-contrib#362]
**Is your feature request related to a problem? Please describe.**
We have a need to send some extra tags to the OpsGenie other than environment, resource, service and event.

**Describe the solution you'd like**
From the code I checked it supports only pre-defined tags (environment, resource, service and event).
I think, we need to change [here](https://github.com/alerta/alerta-contrib/blob/master/plugins/opsgenie/alerta_opsgenie.py#L107)

**Comment by satterly** [comment]
Feel free to fork this repo and modify the plugin how you see fit for your environment. If you make it extensible / configurable then perhaps you could submit your changes back to this repo for everyone to benefit from. Thanks.
