### ISSUE TITLE
[Telegram plugin] Can't find mentioned Jinja2 template

### ISSUE THREAD

**Issue by Beetix** [alerta/alerta-contrib#367]
**Issue Summary**
In the Telegram plugin's `README.md` an example template is mentioned in [Explorer](http://explorer.alerta.io/#/send). Once on the site there doesn't seem to be any Jinja2 template.

**Comment by xpufx** [comment]
I couldn't find it either. However the MS Teams plugin has a little example of the template format. Should work if you create a file and point the telegram plugin to it.

https://github.com/alerta/alerta-contrib/blob/5d79ea4bbda44bde0a578856fa465a89e64dee1d/plugins/msteams/README.md

```MS_TEAMS_SUMMARY_FMT = '<b>[{{ alert.status|capitalize }}]</b> [{{ alert.severity|upper }}] Event {{ alert.event }} on <b>{{ alert.resource }}</b><br>{{ alert.text }}'
```

**Comment by Beetix** [comment]
> I couldn't find it either. However the MS Teams plugin has a little example of the template format. Should work if you create a file and point the telegram plugin to it.
> 
> https://github.com/alerta/alerta-contrib/blob/5d79ea4bbda44bde0a578856fa465a89e64dee1d/plugins/msteams/README.md
> 
> ```
> MS_TEAMS_SUMMARY_FMT = '<b>[{{ alert.status|capitalize }}]</b> [{{ alert.severity|upper }}] Event {{ alert.event }} on <b>{{ alert.resource }}</b><br>{{ alert.text }}'
> ```
> 
> Also, the telegram plugin is already using a template but it's embedded into the script. See "DEFAULT_TMPL" variable in there.

Yes, I ended up using the [`DEFAULT_TMPL` variable](https://github.com/alerta/alerta-contrib/blob/40acf3b7d4658b68131a2fddc1478d3d3483f16b/plugins/telegram/alerta_telegram.py#L13-L22) 😃 Could be worth embedding it or change the link in the `README.md`.

**Comment by darkobas2** [comment]
what are the possible filters we can use ?
