### ISSUE TITLE
Compatibility alerta-mailer with postgresql 

### ISSUE THREAD

**Issue by danielelopez1** [alerta/alerta-contrib#370]
**Is your feature request related to a problem? Please describe.**
Alerta is compliant with postgresql but the alerta-mailer plugin is not. Is there a way to make it compatible? 

**Describe the solution you'd like**
make the alerta-mailer plugin compatible with postgresql

**Additional context**
I'm using latest version of alerta (8.5.0) and last plugin version

**Comment by satterly** [comment]
`mailer` requires an AMQP-compatible message transport. MongoDB supports this, and Postgres doesn't. If you use Postgres as your backend for Alerta API then you will need to run another service to provide the AMQP message transport required by `mailer`. See the README for `kombu` for a list of supported transports ... 

<img width="677" alt="Screenshot 2021-11-09 at 23 35 21" src="https://user-images.githubusercontent.com/615057/141016523-97db6d3b-64ed-4dc7-8b7b-7dc73d211b6e.png">

https://github.com/celery/kombu#transport-comparison
