### ISSUE TITLE
[discussion] moving from Alerta to Keep

### ISSUE THREAD

**Issue by talboren** [alerta/alerta-contrib#398]
Hey folks, wanted to raise this issue for discussion in here since I couldn't get the Alerta maintainers for ~month.
I'm one of the co-founders of https://www.github.com/keephq/keep - we're an Alerta alternative (100% open-source as well) but with workflow automation capabilities.
Since Alerta is no longer (somewhat) maintained and developed, we wanted to offer the community in to Keep and try it out. We offer <very> active maintenance, bugfixes and features building.

The following is a message I left @satterly a while ago
> We're a YC W23 company that acts in the monitoring/o11y space, specifically, doing something quite similar to Alerta but with an automation aspect as well (e.g. we receive alerts from 3rd parties such as prometheus, grafana, ddog, whatever -> we deduplicate/correlate alerts and present them in a single pane of glass -> we allow you to create workflows to be executed upon these alerts)
> I was wondering maybe you'd consider going for a quick conversation with my co-founder and myself on a potential collaboration we can maybe do
> I know Alerta is not so much maintained these days while there's still quite an active community and users who search for improvements, bugfixes and more features
> Would love to hear your opinion about it! lmk
> Cheers!

Would love to get the community opinion on that and see if there's any interest in Keep here.

**Comment by hyberdk** [comment]
Hi @talboren, 

I think it is a little weird to have this discussion on the alerta github.. Sure this project might not be as active as one would like. @satterly has been very clear that he does not have so much time to maintain this as he used to, but on the plus side we do actually have quite a few people in the background using and maintaining it.. Nick as also made it very clear that he is also willing to accept other maintainers into the project.. So its far from dead.. 

From my point of view the strength of Alerta is the plugin system, that is unique, you can make it so whatever you want very easily and it is a very stable and proven product.. exactly what we want for our operation env.

On a personal note, having a discussion here about moving people to keep, I think its misplaced and you should focus on building your product, if its that great Im sure people will come.. that is the benefit of open source. 

Esben

**Comment by sixcare** [comment]
Hi @talboren.

I don't have much to add to this discussion other than that I fully agree with @hyberdk.
Thank you for sharing your product.

If there's nothing more that you would like to discuss about Alerta, I'd suggest we close this issue.

**Comment by talboren** [comment]
> Hi @talboren,
> 
> I think it is a little weird to have this discussion on the alerta github.. Sure this project might not be as active as one would like. @satterly has been very clear that he does not have so much time to maintain this as he used to, but on the plus side we do actually have quite a few people in the background using and maintaining it.. Nick as also made it very clear that he is also willing to accept other maintainers into the project.. So its far from dead..
> 
> From my point of view the strength of Alerta is the plugin system, that is unique, you can make it so whatever you want very easily and it is a very stable and proven product.. exactly what we want for our operation env.
> 
> On a personal note, having a discussion here about moving people to keep, I think its misplaced and you should focus on building your product, if its that great Im sure people will come.. that is the benefit of open source.
> 
> Esben



> Hi @talboren,
> 
> I think it is a little weird to have this discussion on the alerta github.. Sure this project might not be as active as one would like. @satterly has been very clear that he does not have so much time to maintain this as he used to, but on the plus side we do actually have quite a few people in the background using and maintaining it.. Nick as also made it very clear that he is also willing to accept other maintainers into the project.. So its far from dead..
> 
> From my point of view the strength of Alerta is the plugin system, that is unique, you can make it so whatever you want very easily and it is a very stable and proven product.. exactly what we want for our operation env.
> 
> On a personal note, having a discussion here about moving people to keep, I think its misplaced and you should focus on building your product, if its that great Im sure people will come.. that is the benefit of open source.
> 
> Esben

Didn’t have any bad thoughts here. Fully honest I felt like the Slack community is dying, issues are opened but never answered and people asking for help usually don’t get a decent response and thought I’d suggest Keep as an well-maintained OSS alternative.
Appreciate the feedback here folks, closing this for now.

**Comment by talboren** [comment]
> Hi @talboren,
> 
> I think it is a little weird to have this discussion on the alerta github.. Sure this project might not be as active as one would like. @satterly has been very clear that he does not have so much time to maintain this as he used to, but on the plus side we do actually have quite a few people in the background using and maintaining it.. Nick as also made it very clear that he is also willing to accept other maintainers into the project.. So its far from dead..
> 
> From my point of view the strength of Alerta is the plugin system, that is unique, you can make it so whatever you want very easily and it is a very stable and proven product.. exactly what we want for our operation env.
> 
> On a personal note, having a discussion here about moving people to keep, I think its misplaced and you should focus on building your product, if its that great Im sure people will come.. that is the benefit of open source.
> 
> Esben

FWIw @hyberdk 

> From my point of view the strength of Alerta is the plugin system, that is unique, you can make it so whatever you want very easily and it is a very stable and proven product.. exactly what we want for our operation env.

we also support that kind of "plugin system" (we call it providers)
