### ISSUE TITLE
Mailer resets connection to localhost repeatedly

### ISSUE THREAD

**Issue by mikesand** [alerta/alerta-contrib#43]
I'm sure this is a config issue but when I look at the CLI for alerta-mailer I see these lines repeatedly.

```
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: localhost
Resetting dropped connection: localhost
DEBUG:requests.packages.urllib3.connectionpool:"POST /heartbeat HTTP/1.1" 201 484
"POST /heartbeat HTTP/1.1" 201 484
```
It passes the setup.py test and it says it connects successfully to mongo on load. My config looks like this:
```
[DEFAULT]
#timezone = United States/New York
# output = json
profile = production

[profile production]
endpoint = http://alerta.domain.com/api
#key = demo-key

[profile development]
endpoint = http://localhost:8080
debug = yes

[alerta-mailer]
#key = demo-key
mail_to = mike@domain.com
mail_from = alert@domain.com
amqp_url = mongodb://localhost:27017/kombu
dashboard_url = http://localhost
smtp_password = the accout password for the mail from above
debug = True
skip_mta = False
email_type = text
```
Any help would be awesome, thanks!

**Comment by satterly** [comment]
I think this is a feature of python `requests` [sessions](http://docs.python-requests.org/en/master/user/advanced/#session-objects) so I think you can safely ignore this `INFO` messages.

**Comment by satterly** [comment]
Re-open this if it's actually causing you a problem.

**Comment by mikesand** [comment]
I wrote my own service to do the mailers (can't remember why) so it can be closed.

**Comment by satterly** [comment]
No problem. Thanks.
