### ISSUE TITLE
urlmon number of retries

### ISSUE THREAD

**Issue by msupino** [alerta/alerta-contrib#49]
Can urlmon be configured to only create alert after X attempts of failure ? i see 'count' option for check def, but i cant figure out what that does..

**Comment by satterly** [comment]
Yes, that's exactly what `count` is for, isn't it? What happens if you try setting it to "2" or more?

**Comment by msupino** [comment]
hmm.. i set it to 3, but after looking at the code, there is a sleep(10) afterwards, so thats 30 seconds, i though it will be 3 minutes.. testing again

**Comment by satterly** [comment]
There is a `LOOP_EVERY` global variable and a retry interval (which is not a variable and is set to 10 seconds). Probably both of these could be configuration settings.
