### ISSUE TITLE
Slack plugin doesn't work 

### ISSUE THREAD

**Issue by onkarkadam7** [alerta/alerta-contrib#62]
Hi Dev, 

Slack plugin does not work with following config 

in ~/.alertad.conf

CORS_ORIGINS = [
    'http://10.71.1.6'
]

SLACK_WEBHOOK_URL = 'https://hooks.slack.com/services/#######################'

PLUGINS = ['reject' , 'slack']

I get this error when i launch alertad server 
root@devops-infra-003 slack]# alertad
[2016-09-29 14:06:39,425] ERROR in __init__: Server plug-in 'slack' could not be loaded: No module named alerta_slack
[2016-09-29 14:06:39,437] ERROR in __init__: Server plug-in 'slack' could not be loaded: No module named alerta_slack
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
10.70.30.60 - - [29/Sep/2016 14:06:40] "GET /environments?status=open&status=unknown HTTP/1.1" 200 -
10.70.30.60 - - [29/Sep/2016 14:06:40] "GET /alerts/count?status=open&status=unknown HTTP/1.1" 200 -
10.70.30.60 - - [29/Sep/2016 14:06:40] "GET /alerts?status=open&status=unknown HTTP/1.1" 200 -

But i have the alerta-slack pugin installed on my machine : 
[root@devops-infra-003 alerta]# pip freeze
alerta==4.8.1
alerta-server==4.8.5
alerta-slack==0.3.1

Thanks ,
Onkar

**Comment by satterly** [comment]
Thanks for reporting this. It should be fixed now. Try again and let me know.

**Comment by onkarkadam7** [comment]
@satterly  Thanks Nick , i am able to  launch alertad server with slack integration 

Best Regards, 
Onkar
