### ISSUE TITLE
Error while running post-receive plug-in 'alerta_amqp': 'NoneType' object has no attribute 'ensure'

### ISSUE THREAD

**Issue by int32bit** [alerta/alerta-contrib#69]
Not always but sometimes, the alerta failed to publish message to AMQP. It may be a bug in kombu, see [Couldn't apply scheduled task handle_timers: 'NoneType' object has no attribute 'ensure' ](https://github.com/celery/celery/issues/1119). I have met it many times and restart alerta-server will be fine. Is any way to fix or avoid this issue?

**Comment by satterly** [comment]
Is there an error in the Alerta server log or does it just silently fail? If it generates an exception then we could catch it and reconnect, perhaps.

**Comment by int32bit** [comment]
Above error(`Error while running post-receive plug-in 'alerta_amqp': 'NoneType' object has no attribute 'ensure'`) is all I saw from Alerta server log. It's hard to debug because the issue seems occur by random. Now I write a cron task to check status, once it fail I restart the server. It may be not the best solution, but work in my production environment.
